listeners:
- query_port: 25575
  motd: '&1Another Bungee serve'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 45.93.251.40:25565
  max_players: 2000
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: f2004816-dff3-4a36-86a5-928a6f8604d1
player_limit: -1
ip_forward: true
groups:
  YukiHai:
  - admin
  BlueNori:
  - admin
  bluefighter_10:
  - admin
  PxxLLL:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: §4§lValeaGames.de §2| §b1.12.2 §2| §9§l50% §eim §5§lShop §1§lpowerd by §6§lValea-Network.de
    address: localhost:25567
    restricted: false
  cb1:
    motd: §4§lValeaGames.de §2| §b1.12.2 §2| §9§l50% §eim §5§lShop §1§lpowerd by §6§lValea-Network.de
    address: localhost:25566
    restricted: false
